### ISSUE TITLE
Decouple schema & server instantiation from persona

### ISSUE THREAD

**Issue by jgnieuwhof** [overture-stack/persona#67]
The user model is increasingly becoming kids-first specific, which I don't think is inline with the intent of the microservice. I'd like to propose the following changes as a way of addressing app-specific instantiations of persona:

- have persona's main export be an express router, parent applications can use persona's routes in their own server (similar to arranger server)
- parent app can pass in its own user schema
- change tags functionality so that it's configurable. parent app should be able to specify which fields are applicable for tags functionality, and each field should either get its own graphql resolver, or should be a parameter in the tags resolver

@ra-ver, @andricDu - thoughts? I'm happy to take this on if the idea stands.

**Comment by andricDu** [comment]
This sounds great. 

Let's work on a small formal / semi-formal spec just so we can reason about it and point to is when describing what this it.
