### ISSUE TITLE
Fix warnings in persona repo

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/persona#77]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/cf755008-22ac-4e63-a4c6-892969aa30b3)

**Comment by joneubank** [comment]
Published new release with dependency upgrades. 
https://github.com/overture-stack/persona/releases/tag/v1.1.2

**Comment by rosibaj** [comment]
Tested - warnings are resolved and no warnings are visible in repository.  Thanks @joneubank!
