### ISSUE TITLE
Security Upgrade

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/persona#86]
A needed security upgrade has been indicated: 

![image](https://user-images.githubusercontent.com/15824252/92144825-463e4080-ede5-11ea-87b6-55095a69390f.png)

**Comment by hlminh2000** [comment]
Persona isn't deployed in argo. Should we just close this ticket?

**Comment by rosibaj** [comment]
@hlminh2000 no, as this is part of the overture-stack we are obligated to keep this up-to-date as well.

**Comment by rosibaj** [comment]
@hlminh2000 i misunderstood your question! Yes, this can be closed!
