### ISSUE TITLE
Address Persona vulnerabilities

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/persona#91]

**Comment by caravinci** [comment]
Made the changes, yet not quite sure how/where to test it out (to even check whether it works well).
Any pointers are welcome!

**Comment by rosibaj** [comment]
@caravinci we dont have an active project using persona right now - just kidsfirst afaik.  

I see the PR is approved - my best guess here is to just merge and when we use it again figure out if any issues.  <-- @joneubank @hlminh2000 any complaints about this? asking as you guys would be most familiar with persona.

**Comment by caravinci** [comment]
Thanks, @rosibaj 
If kidsfirst has a testing environment, we may be able to deploy this there too.
Maybe @hlminh2000 has some pointers/ideas?

**Comment by rosibaj** [comment]
@caravinci we dont have access to that environment.

**Comment by caravinci** [comment]
That's unfortunate. I'll proceed as instructed, since this app is not in my wheelhouse.

**Comment by caravinci** [comment]
Any help is much appreciated @joneubank! updating deep deps is not my prefer approach either.
As you'll see in the PR's discussion, I agree wholeheartedly with the top-down upgrade approach, yet I tried not going too far beyond the scope I knew was safe, as I wasn't able to test things out... 

That said, Collab is going to be off for maintenance on Monday, and I'll be available all day.
If it works for you, maybe we can setup a chat any time that day?
